package com.tq_ojd.tasks_management.infra.entity;

import java.util.Date;

public class Task {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.ID
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.TITLE
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.DESCRIPTION
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.COMPLETED
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    private Boolean completed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASK.DEADLINE
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    private Date deadline;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.ID
     *
     * @return the value of TASK.ID
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.ID
     *
     * @param id the value for TASK.ID
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.TITLE
     *
     * @return the value of TASK.TITLE
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.TITLE
     *
     * @param title the value for TASK.TITLE
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.DESCRIPTION
     *
     * @return the value of TASK.DESCRIPTION
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.DESCRIPTION
     *
     * @param description the value for TASK.DESCRIPTION
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.COMPLETED
     *
     * @return the value of TASK.COMPLETED
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    public Boolean getCompleted() {
        return completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.COMPLETED
     *
     * @param completed the value for TASK.COMPLETED
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    public void setCompleted(Boolean completed) {
        this.completed = completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASK.DEADLINE
     *
     * @return the value of TASK.DEADLINE
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASK.DEADLINE
     *
     * @param deadline the value for TASK.DEADLINE
     *
     * @mbg.generated Fri Jul 12 16:37:25 JST 2024
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }
}