package com.tq_ojd.tasks_management.infra.entity;

import java.util.Date;

import lombok.Data;

@Data
public class Tasks {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.ID
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.TITLE
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.DESCRIPTION
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.COMPLETED
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    private Boolean completed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TASKS.DEADLINE
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    private Date deadline;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.ID
     *
     * @return the value of TASKS.ID
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.ID
     *
     * @param id the value for TASKS.ID
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.TITLE
     *
     * @return the value of TASKS.TITLE
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.TITLE
     *
     * @param title the value for TASKS.TITLE
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.DESCRIPTION
     *
     * @return the value of TASKS.DESCRIPTION
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.DESCRIPTION
     *
     * @param description the value for TASKS.DESCRIPTION
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.COMPLETED
     *
     * @return the value of TASKS.COMPLETED
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    public Boolean getCompleted() {
        return completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.COMPLETED
     *
     * @param completed the value for TASKS.COMPLETED
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    public void setCompleted(Boolean completed) {
        this.completed = completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TASKS.DEADLINE
     *
     * @return the value of TASKS.DEADLINE
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    public Date getDeadline() {
        return deadline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TASKS.DEADLINE
     *
     * @param deadline the value for TASKS.DEADLINE
     *
     * @mbg.generated Tue Jul 09 14:29:35 JST 2024
     */
    public void setDeadline(Date deadline) {
        this.deadline = deadline;
    }
}